import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => ['en', 'xh', 'zu', 'fr', 'hi', 'de'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? xhText = '',
    String? zuText = '',
    String? frText = '',
    String? hiText = '',
    String? deText = '',
  }) =>
      [enText, xhText, zuText, frText, hiText, deText][languageIndex] ?? '';
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // loginPage
  {
    '79mdeqny': {
      'en': 'Login',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'dqs0nkv7': {
      'en': 'Email Address',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'phhyz4dy': {
      'en': 'Enter your email...',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'ya8bg0ec': {
      'en': 'Password',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'yonvafvg': {
      'en': 'Enter your password...',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '1guqe8v8': {
      'en': 'Login',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '18t8mclc': {
      'en': 'Forgot Password',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'v9s0icgd': {
      'en': 'Continue as Guest',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'wb1h583s': {
      'en': 'Create account',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'lluuxmlt': {
      'en': 'Email Address',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'rtkag24c': {
      'en': 'Enter your email...',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'ig20yu83': {
      'en': 'Password',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'v12lomi4': {
      'en': 'Enter your password...',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'ag75i4po': {
      'en': 'Confirm Password',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'aq9mecg6': {
      'en': 'Enter your password...',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'hvvgjnth': {
      'en': 'Create Account',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '6qz6hkwa': {
      'en': 'Continue as Guest',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'aoqx0esf': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
  },
  // completeProfile
  {
    'vhos3n5v': {
      'en': 'Complete Profile',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'vn59t3lc': {
      'en': 'Upload a photo for us to easily identify you.',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'ky4q5xkh': {
      'en': 'Your Name',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'jdqzlujf': {
      'en': 'Please enter your name...',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '9v1r1pqp': {
      'en': 'Your Age',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'xzi5ncbe': {
      'en': 'i.e. 34',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'mjplyn1d': {
      'en': 'Interests',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '8ps84aoz': {
      'en': 'What things do you love to do?',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '29b9zw3p': {
      'en': 'Your Gender',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '9ge53rek': {
      'en': 'Male',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '22fvsu14': {
      'en': 'Female',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '70r85wux': {
      'en': 'Add Another Profile',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'sk5ywths': {
      'en': 'Complete Profile',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '7ml3klc1': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
  },
  // forgotPassword
  {
    'o7uqaoda': {
      'en': 'Forgot Password',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '2trafybl': {
      'en':
          'Enter the email associated with your account and we will send you a verification code.',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '29c83sid': {
      'en': 'Email Address',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '59892fu0': {
      'en': 'Enter your email...',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'nbjcsir2': {
      'en': 'Send Reset Link',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '83dfjqbr': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
  },
  // addAnotherProfile
  {
    'y2megfai': {
      'en': 'Add Another Profile',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'e5b8eikk': {
      'en': 'Upload a photo for us to easily identify this person.',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'pl88qnt9': {
      'en': 'Persons Name',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '3oy43p2x': {
      'en': 'Official name here...',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'ydzomwyu': {
      'en': 'Persons Age',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'p4lcurph': {
      'en': 'i.e. 34',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'gwo3ypzt': {
      'en': 'Persons Ailments',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'ptb3prty': {
      'en': 'What types of allergies do they have..',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'bxn0ngb8': {
      'en': 'Location',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'cl3rs2pv': {
      'en': 'Please enter a valid email...',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'u58v4p0v': {
      'en': 'Persons Birth Sex',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '93vm81rg': {
      'en': 'Male',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '0r8efe7u': {
      'en': 'Female',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'i9l6ovy1': {
      'en': 'Undisclosed',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'ugnrf8vo': {
      'en': 'Complete Profile',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'mi7xkat9': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
  },
  // onboarding
  {
    'jla3sn2z': {
      'en': 'Get some lovingos',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '7w1ljgqu': {
      'en':
          'Always have a ready answer when your aunt or concerned parents ask when you get married.',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'ygctr3ls': {
      'en': 'Schedule Appointments',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'kbchjppa': {
      'en':
          'Easily schedule appointments for checkups,  routine procedures, etc.',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'yiaj3rrp': {
      'en': 'Doctor in your pocket',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'dxct68jd': {
      'en': 'Easily find symptoms and common factors that affect you daily.',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'qx72wh1w': {
      'en': 'Continue',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '3akqu1n5': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
  },
  // homePage
  {
    '3bvws8pw': {
      'en': 'Good Morning',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'imgms6dg': {
      'en': 'Your next appointment',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'qh9wwyx6': {
      'en': 'For',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '4i7efn8i': {
      'en': 'Book a date',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'c9r6e02i': {
      'en': 'Schedule a day with your potential friend and hangout.',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'huye4258': {
      'en': 'Make a Call ',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'tsd5wbce': {
      'en': 'Make a direct call in order to schedule your appointment.',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'ot75j8xt': {
      'en': 'Send a message',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'ga8tujoy': {
      'en':
          'Send them a message directly and they\'ll get back to you within 24 hours.',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'p009wrzf': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
  },
  // myAppointments
  {
    '5sn0mz8g': {
      'en': 'Appointments',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'h138h7kx': {
      'en': 'My Appointments',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'k8l3v1em': {
      'en': 'Dates',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
  },
  // appointmentDetails
  {
    'c6z4oenz': {
      'en': 'Details',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'u2n4s6va': {
      'en': 'Type of Appointment',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'l3jwdzkq': {
      'en': 'What’s the problem?',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'k5447rvw': {
      'en': 'For',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'yqxl85od': {
      'en': 'When',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'f74n00hw': {
      'en': 'Reschedule',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'izlgoa83': {
      'en': 'Cancel Appointment',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'bc8zlxxj': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
  },
  // profilePage
  {
    '2k36tw7o': {
      'en': 'Ailments',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '2v99j5zb': {
      'en': 'Next Appointment',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'hfri4qit': {
      'en': 'Aug 20, 2021',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'ayn8bu4d': {
      'en': 'Switch to Dark Mode',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'sj09uhio': {
      'en': 'Switch to Light Mode',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'wsya3gbn': {
      'en': 'Past Appointments',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'ue53emj4': {
      'en': 'For',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'lkr2j4gd': {
      'en': 'Profile',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
  },
  // editProfile
  {
    'slmtgwcd': {
      'en': 'Edit Profile',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '9e6wu496': {
      'en': 'Change Photo',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'bzjnlnkq': {
      'en': 'Your Name',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'ow0u8160': {
      'en': 'Please enter a valid number...',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'mr9ug4b4': {
      'en': 'Email Address',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    't24371sh': {
      'en': 'Your email',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'bc8uf7bc': {
      'en': 'Your Age',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'ckgao49f': {
      'en': 'i.e. 34',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'zyauz53b': {
      'en': 'Ailments',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'oudz4uc1': {
      'en': 'What types of allergies do you have..',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '0tfffnjv': {
      'en': 'Your Birth Sex',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'wwhul999': {
      'en': 'Male',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '0ekkoxv1': {
      'en': 'Female',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '9rhze95x': {
      'en': 'Undisclosed',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'hsrkup3b': {
      'en': 'Update profile',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'br6bgu1r': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
  },
  // findInterests
  {
    'yv5ud1xc': {
      'en': 'Interests',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '2d4s4e21': {
      'en': 'Search interests…',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '2saap3yz': {
      'en': 'Swimming, Music, Poetry etc...',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'sb0y4glx': {
      'en': '[Interest Name]',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'ld28yl9v': {
      'en':
          'Find all the poeple who love what you love and are willing to do it with you; hangout quite often',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '113sjszr': {
      'en': '[Interest Name]',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'zsalluip': {
      'en':
          'Find all the poeple who love what you love and are willing to do it with you; hangout quite often',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '6rui6xg6': {
      'en': '[Interest Name]',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '5rzmmoy2': {
      'en':
          'Find all the poeple who love what you love and are willing to do it with you; hangout quite often',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'ij9r4n4i': {
      'en': '[Interest Name]',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '1z60uvu9': {
      'en':
          'Find all the poeple who love what you love and are willing to do it with you; hangout quite often',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'z8bd7aun': {
      'en': 'Interests',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
  },
  // appointmentDetailsProfile
  {
    'amwzq4ui': {
      'en': 'Details',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'wlwrjjpp': {
      'en': 'Type of Appointment',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '0cs53dyw': {
      'en': 'What’s the problem?',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'xv1unbr7': {
      'en': 'For',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'ah50zdbc': {
      'en': 'When',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '5btulg36': {
      'en': 'Remove Appointment',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'lo9aizmz': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
  },
  // bookAppointment
  {
    '1h2s5653': {
      'en': 'Book Appointment',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '3o5847a8': {
      'en':
          'Fill out the information below in order to book your appointment with our office.',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'i1uzq0q3': {
      'en': 'Emails will be sent to:',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'bqqsnivx': {
      'en': 'Booking For',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'lixtva8m': {
      'en': 'Doctors Visit',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'irf3vhs2': {
      'en': 'Routine Checkup',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'pd208xwf': {
      'en': 'Scan/Update',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '9icwzzgf': {
      'en': 'Type of Appointment',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '97cybfk0': {
      'en': 'What\'s the problem?',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'agu1vc05': {
      'en': 'Choose Date & Time',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'x74ownw8': {
      'en': 'Cancel',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'bop88gy3': {
      'en': 'Book Now',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
  },
  // bookingOld
  {
    'ch1gly36': {
      'en': 'Book Appointment',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'fu8k7nsv': {
      'en':
          'Fill out the information below in order to book your appointment with our office.',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '9occx1od': {
      'en': 'Email Address',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'gj1m3dfk': {
      'en': 'Booking For',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'tgdsuc88': {
      'en': 'Doctors Visit',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'eu7pxtiu': {
      'en': 'Routine Checkup',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '4w3p5nqe': {
      'en': 'Scan/Update',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'e9m5tl5i': {
      'en': 'Type of Appointment',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '6s4khhng': {
      'en': 'What\'s the problem?',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '6uasjtji': {
      'en': 'Choose Date',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '5ckci0u8': {
      'en': 'Cancel',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'wthjiykt': {
      'en': 'Book Now',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
  },
  // editBooking
  {
    'esjgkfiu': {
      'en': 'Edit Appointment',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '6rsebflc': {
      'en': 'Edit the fields below in order to change your appointment.',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '50bqodr2': {
      'en': 'Emails will be sent to:',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'cmc9kdap': {
      'en': 'Booking For',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'hzqzos2f': {
      'en': 'Type of Appointment',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'zb97ut7g': {
      'en': 'Doctors Visit',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '955dbnj6': {
      'en': 'Routine Checkup',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'yt6f7w82': {
      'en': 'Scan/Update',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'sp9ujkx4': {
      'en': 'What\'s the problem?',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '13xiq0lp': {
      'en': 'Choose Date',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'puoumlh3': {
      'en': 'Cancel',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '7l2aenkl': {
      'en': 'Save Changes',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
  },
  // EmptyList
  {
    'uch98ltn': {
      'en': 'No Appointments!',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '5jlaleeg': {
      'en':
          'You are all caught! No appointments scheduled, need an appointment? Schedule one now.',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'znnx57z2': {
      'en': 'Schedule',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
  },
  // Miscellaneous
  {
    '30i0u2vb': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '6jkv57bk': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'yy62f161': {
      'en': 'Please allow app to access your device bluetooth',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'v7ohibiw': {
      'en': 'Please allow app to access your device biometrics',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'b5oitgtt': {
      'en': 'Please allow app to access your calendar',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'kzz3xx0e': {
      'en':
          'In order to connect to more people this app needs access to your contacts',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'u5kdyedw': {
      'en': 'Please allow app to access your device location',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '2qpgdmd5': {
      'en': 'Allow app to use microphone',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'zsc3oe7s': {
      'en': 'Allow app to send you notifications',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'ajrz52pu': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'pl5yr48t': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '1hqai0mn': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '1m6e85qe': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'sbk0ufl0': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '3zsco4cs': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'b5xpails': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'w0ezzbqh': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '54srny4g': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'f8c5uwz1': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'o7h56a7c': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'fn0tzkj8': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'ecwpnops': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'vyqwfrb0': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'qndjd3uz': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'qgp7zq9w': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'w6awsk6d': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    'o4ew4ycq': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '3sj1p6pu': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
    '24b0l1lo': {
      'en': '',
      'de': '',
      'fr': '',
      'hi': '',
      'xh': '',
      'zu': '',
    },
  },
].reduce((a, b) => a..addAll(b));
